[package]
name = "raytracer"
version = "0.1.0"
authors = ["Sampo Siitonen <sampo.siitonen@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23"
nalgebra = "0.21"
rand = {version = "0.7", features = ["small_rng"]}

[profile.release]
debug = true